### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yutingsdu** [ishinder/EASTR#13]
I got the following error log when running eastr, would you please help me?

faidx: invalid option -- 'r'

Usage:   samtools faidx <file.fa|file.fa.gz> [<reg> [...]]

Traceback (most recent call last):
  File "/home/yuting/anaconda3/bin/eastr", line 8, in <module>
    sys.exit(main())
  File "/home/yuting/anaconda3/lib/python3.9/site-packages/EASTR/run_eastr.py", line 257, in main
    spurious_dict = get_spurious_introns.get_spurious_junctions(scoring, k, w, m, overhang, min_duplicate_exon_length, bt2_index, bt2_k,
  File "/home/yuting/anaconda3/lib/python3.9/site-packages/EASTR/get_spurious_introns.py", line 239, in get_spurious_junctions
    self_introns = get_self_aligned_introns(introns, seqs, overhang, k, w, m, scoring)
  File "/home/yuting/anaconda3/lib/python3.9/site-packages/EASTR/get_spurious_introns.py", line 16, in get_self_aligned_introns
    rseq = seqs[introns[key]['jstart']]
KeyError: 'chr1:14780-14879'

**Comment by yutingsdu** [comment]
It is version 1.3.1.

**Comment by ishinder** [comment]
@yutingsdu - to use eastr, please udpate samtools to the latest version (1.19.1). Let me know if you're having any other issues :)
